dependencies:
    # - <organization(github account)/repo>@<version>
    - OpenZeppelin/openzeppelin-contracts@4.5.0
    - smartcontractkit/chainlink-brownie-contracts@0.4.0
compiler:
    solc:
        remappings:
            - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"
            - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.0"
dotenv: .env
networks:
    default: development
    development:
        gas_price: 17000000000 # in order to fulfill the tx on hardhat node
    mainnet:
        verify: False
    rinkeby:
        verify: False
    kovan:
        verify: False
    polygon:
        verify: False
wallets:
    mainnet:
        from_key: ${PRIVATE_KEY_MAIN}
    rinkeby:
        from_key: ${PRIVATE_KEY_TEST}
    kovan:
        from_key: ${PRIVATE_KEY_TEST}
    polygon:
        from_key: ${PRIVATE_KEY_MAIN}
